name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # - name: Run tests
    #   run: npm test
      
    # - name: Run linter
    #   run: npm run lint

    - name: Build project
      run: npm run build

    - name: Copy calculator files
      run: |
        cp tile-calculator.html carpet-calculator.html hardwood-calculator.html baseboard-calculator.html subfloor-calculator.html dist/
        cp tile-calculator.js carpet-calculator.js hardwood-calculator.js baseboard-calculator.js subfloor-calculator.js dist/
        cp styles.css dist/
        cp about.html blog.html contact.html guides.html faq.html privacy.html terms.html dist/

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
