name: Lighthouse CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Start local preview server
        run: |
          npx vite preview --port 4173 --strictPort &
          sleep 3

      - name: Wait for GitHub Pages (deployed site)
        run: |
          URL=https://the-wise-men.github.io/sq2ft-calculators/
          echo "Waiting for $URL to return 200..."
          for i in {1..60}; do
            CODE=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
            if [ "$CODE" = "200" ]; then echo "Site is up"; break; fi
            echo "Got $CODE, retrying in 5s..."; sleep 5;
            if [ $i -eq 60 ]; then echo "Timed out waiting for $URL" >&2; exit 1; fi
          done

      - name: Install Lighthouse CI
        run: |
          npm i -g @lhci/cli@0.13.x

      - name: Run LHCI (homepage)
        run: |
          lhci collect --url=https://the-wise-men.github.io/sq2ft-calculators/ --numberOfRuns=1 --settings.formFactor=mobile --settings.screenEmulation.mobile=true --settings.throttlingMethod=simulate
          cp "$(ls -t .lighthouseci/*.json | head -n 1)" lhr-home.json
          lhci assert --config=lighthouserc.json

      - name: Run LHCI (tile calculator)
        run: |
          lhci collect --url=https://the-wise-men.github.io/sq2ft-calculators/tile-calculator.html --numberOfRuns=1 --settings.formFactor=mobile --settings.screenEmulation.mobile=true --settings.throttlingMethod=simulate
          cp "$(ls -t .lighthouseci/*.json | head -n 1)" lhr-tile.json
          lhci assert --config=lighthouserc.json

      - name: Run LHCI (homepage desktop)
        run: |
          lhci collect --url=https://the-wise-men.github.io/sq2ft-calculators/ --numberOfRuns=1 --settings.formFactor=desktop --settings.screenEmulation.mobile=false --settings.throttlingMethod=simulate
          cp "$(ls -t .lighthouseci/*.json | head -n 1)" lhr-home-desktop.json
          lhci assert --config=lighthouserc.json

      - name: Run LHCI (tile calculator desktop)
        run: |
          lhci collect --url=https://the-wise-men.github.io/sq2ft-calculators/tile-calculator.html --numberOfRuns=1 --settings.formFactor=desktop --settings.screenEmulation.mobile=false --settings.throttlingMethod=simulate
          cp "$(ls -t .lighthouseci/*.json | head -n 1)" lhr-tile-desktop.json
          lhci assert --config=lighthouserc.json

      - name: Run LHCI local (homepage mobile)
        run: |
          lhci collect --url=http://localhost:4173/sq2ft-calculators/ --numberOfRuns=1 --settings.formFactor=mobile --settings.screenEmulation.mobile=true --settings.throttlingMethod=simulate
          cp "$(ls -t .lighthouseci/*.json | head -n 1)" lhr-home-local.json
          lhci assert --config=lighthouserc.json

      - name: Run LHCI local (tile mobile)
        run: |
          lhci collect --url=http://localhost:4173/sq2ft-calculators/tile-calculator.html --numberOfRuns=1 --settings.formFactor=mobile --settings.screenEmulation.mobile=true --settings.throttlingMethod=simulate
          cp "$(ls -t .lighthouseci/*.json | head -n 1)" lhr-tile-local.json
          lhci assert --config=lighthouserc.json

      - name: Run LHCI local (homepage desktop)
        run: |
          lhci collect --url=http://localhost:4173/sq2ft-calculators/ --numberOfRuns=1 --settings.formFactor=desktop --settings.screenEmulation.mobile=false --settings.throttlingMethod=simulate
          cp "$(ls -t .lighthouseci/*.json | head -n 1)" lhr-home-desktop-local.json
          lhci assert --config=lighthouserc.json

      - name: Run LHCI local (tile desktop)
        run: |
          lhci collect --url=http://localhost:4173/sq2ft-calculators/tile-calculator.html --numberOfRuns=1 --settings.formFactor=desktop --settings.screenEmulation.mobile=false --settings.throttlingMethod=simulate
          cp "$(ls -t .lighthouseci/*.json | head -n 1)" lhr-tile-desktop-local.json
          lhci assert --config=lighthouserc.json

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: |
            lhr-home.json
            lhr-tile.json
            lhr-home-desktop.json
            lhr-tile-desktop.json
            lhr-home-local.json
            lhr-tile-local.json
            lhr-home-desktop-local.json
            lhr-tile-desktop-local.json
            .lighthouseci/*.json
            .lighthouseci/*.html

      - name: Summarize category scores
        run: |
          node -e "const fs=require('fs'); const f=p=>JSON.parse(fs.readFileSync(p,'utf8')); const fmt=o=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k,Math.round((v.score||0)*100)])); const h=f('lhr-home.json').categories; const t=f('lhr-tile.json').categories; const hd=f('lhr-home-desktop.json').categories; const td=f('lhr-tile-desktop.json').categories; const hl=f('lhr-home-local.json').categories; const tl=f('lhr-tile-local.json').categories; const hdl=f('lhr-home-desktop-local.json').categories; const tdl=f('lhr-tile-desktop-local.json').categories; console.log('Deployed — Home (mobile):',fmt(h)); console.log('Deployed — Tile (mobile):',fmt(t)); console.log('Deployed — Home (desktop):',fmt(hd)); console.log('Deployed — Tile (desktop):',fmt(td)); console.log('Local — Home (mobile):',fmt(hl)); console.log('Local — Tile (mobile):',fmt(tl)); console.log('Local — Home (desktop):',fmt(hdl)); console.log('Local — Tile (desktop):',fmt(tdl));"

