name: Lighthouse CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Start local preview server
        run: |
          npx vite preview --port 4173 --strictPort &
          sleep 3

      - name: Wait for Pages deploy
        uses: jakepartusch/wait-for-netlify-action@v1.4
        with:
          site_url: https://the-wise-men.github.io/sq2ft-calculators/
          max_timeout: 180000

      - name: Install Lighthouse CI
        run: |
          npm i -g @lhci/cli@0.13.x

      - name: Run LHCI (homepage)
        run: |
          lhci collect --url=https://the-wise-men.github.io/sq2ft-calculators/ --numberOfRuns=1 --settings.emulatedFormFactor=mobile --settings.screenEmulation.mobile=true --settings.throttlingMethod=simulate --output=json --output-path=./lhr-home.json
          lhci assert --config=lighthouserc.json

      - name: Run LHCI (tile calculator)
        run: |
          lhci collect --url=https://the-wise-men.github.io/sq2ft-calculators/tile-calculator.html --numberOfRuns=1 --settings.emulatedFormFactor=mobile --settings.screenEmulation.mobile=true --settings.throttlingMethod=simulate --output=json --output-path=./lhr-tile.json
          lhci assert --config=lighthouserc.json

      - name: Run LHCI (homepage desktop)
        run: |
          lhci collect --url=https://the-wise-men.github.io/sq2ft-calculators/ --numberOfRuns=1 --settings.emulatedFormFactor=desktop --settings.screenEmulation.mobile=false --settings.throttlingMethod=simulate --output=json --output-path=./lhr-home-desktop.json
          lhci assert --config=lighthouserc.json

      - name: Run LHCI (tile calculator desktop)
        run: |
          lhci collect --url=https://the-wise-men.github.io/sq2ft-calculators/tile-calculator.html --numberOfRuns=1 --settings.emulatedFormFactor=desktop --settings.screenEmulation.mobile=false --settings.throttlingMethod=simulate --output=json --output-path=./lhr-tile-desktop.json
          lhci assert --config=lighthouserc.json

      - name: Run LHCI local (homepage mobile)
        run: |
          lhci collect --url=http://localhost:4173/ --numberOfRuns=1 --settings.emulatedFormFactor=mobile --settings.screenEmulation.mobile=true --settings.throttlingMethod=simulate --output=json --output-path=./lhr-home-local.json
          lhci assert --config=lighthouserc.json

      - name: Run LHCI local (tile mobile)
        run: |
          lhci collect --url=http://localhost:4173/tile-calculator.html --numberOfRuns=1 --settings.emulatedFormFactor=mobile --settings.screenEmulation.mobile=true --settings.throttlingMethod=simulate --output=json --output-path=./lhr-tile-local.json
          lhci assert --config=lighthouserc.json

      - name: Run LHCI local (homepage desktop)
        run: |
          lhci collect --url=http://localhost:4173/ --numberOfRuns=1 --settings.emulatedFormFactor=desktop --settings.screenEmulation.mobile=false --settings.throttlingMethod=simulate --output=json --output-path=./lhr-home-desktop-local.json
          lhci assert --config=lighthouserc.json

      - name: Run LHCI local (tile desktop)
        run: |
          lhci collect --url=http://localhost:4173/tile-calculator.html --numberOfRuns=1 --settings.emulatedFormFactor=desktop --settings.screenEmulation.mobile=false --settings.throttlingMethod=simulate --output=json --output-path=./lhr-tile-desktop-local.json
          lhci assert --config=lighthouserc.json

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: |
            lhr-home.json
            lhr-tile.json
            lhr-home-desktop.json
            lhr-tile-desktop.json
            lhr-home-local.json
            lhr-tile-local.json
            lhr-home-desktop-local.json
            lhr-tile-desktop-local.json

      - name: Summarize category scores
        run: |
          node -e "const fs=require('fs'); const f=p=>JSON.parse(fs.readFileSync(p,'utf8')); const fmt=o=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k,Math.round((v.score||0)*100)])); const h=f('lhr-home.json').categories; const t=f('lhr-tile.json').categories; const hd=f('lhr-home-desktop.json').categories; const td=f('lhr-tile-desktop.json').categories; const hl=f('lhr-home-local.json').categories; const tl=f('lhr-tile-local.json').categories; const hdl=f('lhr-home-desktop-local.json').categories; const tdl=f('lhr-tile-desktop-local.json').categories; console.log('Deployed — Home (mobile):',fmt(h)); console.log('Deployed — Tile (mobile):',fmt(t)); console.log('Deployed — Home (desktop):',fmt(hd)); console.log('Deployed — Tile (desktop):',fmt(td)); console.log('Local — Home (mobile):',fmt(hl)); console.log('Local — Tile (mobile):',fmt(tl)); console.log('Local — Home (desktop):',fmt(hdl)); console.log('Local — Tile (desktop):',fmt(tdl));"

