name: Lighthouse CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Pages deploy
        uses: jakepartusch/wait-for-netlify-action@v1.4
        with:
          site_url: https://the-wise-men.github.io/sq2ft-calculators/
          max_timeout: 180000

      - name: Install Lighthouse CI
        run: |
          npm i -g @lhci/cli@0.13.x

      - name: Run LHCI (homepage)
        run: |
          lhci collect --url=https://the-wise-men.github.io/sq2ft-calculators/ --numberOfRuns=1 --settings.emulatedFormFactor=mobile --settings.screenEmulation.mobile=true --settings.throttlingMethod=simulate --output=json --output-path=./lhr-home.json
          lhci assert --assertions.category-performance=warn --assertions.category-seo=warn --assertions.category-accessibility=warn || true

      - name: Run LHCI (tile calculator)
        run: |
          lhci collect --url=https://the-wise-men.github.io/sq2ft-calculators/tile-calculator.html --numberOfRuns=1 --settings.emulatedFormFactor=mobile --settings.screenEmulation.mobile=true --settings.throttlingMethod=simulate --output=json --output-path=./lhr-tile.json
          lhci assert --assertions.category-performance=warn --assertions.category-seo=warn --assertions.category-accessibility=warn || true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: |
            lhr-home.json
            lhr-tile.json

      - name: Summarize category scores
        run: |
          node -e "const fs=require('fs'); const f=p=>JSON.parse(fs.readFileSync(p,'utf8')); const fmt=o=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k,Math.round((v.score||0)*100)])); const h=f('lhr-home.json').categories; const t=f('lhr-tile.json').categories; console.log('Home:',fmt(h)); console.log('Tile:',fmt(t));"

